### PR TITLE
Merge changes from my fork

### PR DESCRIPTION
**Pull request by Panquesito7**
See [changelog](https://github.com/Panquesito7/vehicle_mash/blob/master/README.md#changelog) for information.

### CODE REVIEW

**Comment by Panquesito7** [comment]
@sofar.

**Comment by Panquesito7** [comment]
@sofar, it is been 1 month, will this be merged?

**Comment by sofar** [comment]
@Panquesito7 I've given you push access. Double check your changes and then go ahead and merge.

**Comment by Panquesito7** [comment]
@sofar Thank you for the invitation to the repository! 🙂

Note that minetest-mods/lib_mount#1 must be merged in order to
make this mod to work, as it calls access to new API implemented there.

**Comment by Panquesito7** [comment]
I'll merge this PR. This is the [`lib_mount`](https://github.com/Panquesito7/lib_mount) version that should be used.
It is specified in `README.md`, so, I see no problem with it.

Once reviews are addressed on [minetest-mods/`lib_mount`](https://github.com/minetest-mods/lib_mount/pull/1), we can update the `README.md` as well. 🙂

**Pull request merged**
