### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by VanessaE**

### CODE REVIEW

**Comment by blert2112** [comment]
Thank you. Again. :)

**Comment by VanessaE** [comment]
No prob.  I think everything has been covered now. :)

**Comment by bell07** [comment]
I do not see the patch in upstream :(

**Comment by blert2112** [comment]
Line 132 in 'init.lua'. Was just a typo in a file name. A letter was capitalized causing a crash on Linux machines. It has been fixed.

**Comment by blert2112** [comment]
Crap! You are correct! The typo is still there. I'm on it.

**Pull request closed without merging**
