### PR TITLE
Update framework.lua

### PR DESCRIPTION
**Pull request by shivajiva101**
adds ownership to cars. First player to drive the car becomes the owner until they dig the car and place it again allowing for transfer of ownership. Passengers are allowed if the owner is driving.
Prevents cars being stolen if they have an owner

### CODE REVIEW

**Comment by wilkgr76** [comment]
An interesting idea would be to have named cars (so that you can see who's it is without clicking). I know that the nametag mod (https://github.com/BlockMen/nametag/) works for cars, so perhaps do something similar...?
Nametag mod on F1:
screenshot_20160813_093455

**Comment by blert2112** [comment]
Nice idea. I'll work on it.

**Comment by wilkgr76** [comment]
I'm trying to do it myself ATM, so I guess the race is on? 😛

**Comment by blert2112** [comment]
I welcome all pull requests. Just FYI... There will be a big update pushed sometime tomorrow. I converted this mod over to use my lib_mount mod because the code is nearly identical and I hate code duplication.

**Comment by wilkgr76** [comment]
Ok...will wait then :smile:

**Comment by blert2112** [comment]
Ok, updates are up. You will need lib_mount.

**Pull request merged**
